server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: blob: http://localhost:3000 https://*.amazonaws.com; media-src 'self' blob: http://localhost:3000 https://*.amazonaws.com; connect-src 'self' http://localhost:3000 https://*.amazonaws.com; frame-src 'self' blob: http://localhost:3000 https://*.amazonaws.com; object-src 'self' blob: http://localhost:3000 https://*.amazonaws.com; worker-src 'self' blob:;";

    location / {
        try_files $uri $uri/ /index.html;
    }
}